# Safe Work Procedure Generator Configuration
# This file contains all configurable settings for the application

# File system paths configuration
paths:
  # Default folder containing template PDF files
  default_template_folder: "T:\\Safe Work Procedures\\SOP-SWP-RA-ECP - templates"
  
  # Default folder containing work procedure documents
  default_work_procedure_folder: "T:\\Safe Work Procedures"
  
  # Path to the Chrome/Chromium browser executable for automation
  browser_path: "C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe"

# Debug/development specific paths (used when testing)
debug_paths:
  # Source PDF file for testing
  source_pdf: "D:\\OneDrive\\Documents\\jp\\examples_new\\WCB and PCF Master -04-10-2023 MAIN2 - Copy_UP2.pdf"
  
  # Template folder for development/testing
  template_folder: "D:\\OneDrive\\Documents\\jp\\examples_new\\Templates"
  
  # Work procedure folder for development/testing
  work_procedure_folder: "D:\\OneDrive\\Documents\\jp\\examples_new\\Procedure Documents"

# User interface settings
ui_settings:
  # Default window size [width, height] for the main application
  default_window_size: [800, 600]
  
  # Browser viewport dimensions for web automation
  viewport_width: 1400
  viewport_height: 900

# Timeout configurations (all values in milliseconds unless specified)
timeouts:
  # Delay between individual field interactions to prevent issues
  field_interaction_delay: 50
  
  # Timeout for quick operations
  short_timeout: 300
  
  # Standard timeout for most operations
  standard_timeout: 1000
  
  # Wait time after page navigation
  navigation_timeout: 500
  
  # Threshold to detect significant DOM changes
  content_change_threshold: 500
  
  # How often to check for next button availability (seconds)
  next_button_check_interval: 5
  
  # How often to perform periodic page checks (seconds)
  periodic_page_check_interval: 10

# WorkSafe BC specific configuration
worksafe_bc:
  # URL for the WorkSafe BC Notice of Project system
  url: "https://prevnop.online.worksafebc.com/"

# PDF form field names and constants
field_names:
  # Field name for template selection dropdown
  template_select_field: "TEMPLATE_SELECT"
  
  # Field name pattern for work procedure selection (X gets replaced with number)
  work_procedure_select_field: "WORK_PROCEDURE_SELECTX"
  
  # Hidden field that stores all work procedure options
  work_procedure_select_all_field: "WORK_PROCEDURE_SELECT_ALL"
  
  # The text field to input the work procedure text
  # In the template PDF, name the text field "SWP", "SWP2", "SWP3" etc for each cooresponding page
  # Additional pages are automatically added as needed
  # X is replaced by a number, except for the first page, which has no number
  work_procedure_text_field: "SWPX"
  
  # Maximum number of work procedure fields supported
  num_work_procedure_fields: 12

# Notice of Project (NOP) form configuration
NOP:
  # Data transformations for converting between data formats and form values
  transformations:
    # Risk calculation mapping
    RISK_CALC:
      type: "map"
      values:
        High: "RiskCalcHigh"
        Moderate: "RiskCalcMod"
        Low: "RiskCalcLow"
    
    # Duration time calculation (dynamic field based on which duration field has data)
    _DURATION_TIME:
      type: "dynamic"
      source_fields: ["DURATION_HOURS", "DURATION_DAYS", "DURATION_MONTHS", "DURATION_YEARS"]
    
    # Duration unit selection (automatically determined based on which duration field is used)
    DURATION_UNIT:
      type: "dynamic"
      source_fields: ["DURATION_HOURS", "DURATION_DAYS", "DURATION_MONTHS", "DURATION_YEARS"]
      value_map:
        DURATION_HOURS: "Hours"
        DURATION_DAYS: "Days"
        DURATION_MONTHS: "Months"
        DURATION_YEARS: "Years"

  # Page-by-page form field mappings
  pages:
    # Page 1: General Information
    - general information:
        projectType:
          type: "radio"
          data_key: "PROJECT_TYPE"
        firstName:
          type: "text"
          data_key: "FIRST_NAME"
        lastName:
          type: "text"
          data_key: "LAST_NAME"
        inputPhone:
          type: "text"
          data_key: "PHONE"
        email:
          type: "text"
          data_key: "EMAIL"
    
    # Page 2: Worksite Details
    - worksite details:
        SearchTextField:
          type: "address"
          data_key: "ADDRESS"
        detailsText:
          type: "textarea"
          data_key: "ADDRESS_DETAILS"
        myDate:
          type: "date"
          data_key: "WORK_DATE"
        durationTime:
          type: "number"
          data_key: "_DURATION_TIME"
        durationUnit:
          type: "select"
          data_key: "DURATION_UNIT"
        startTime:
          type: "select"
          data_key: "START_TIME"
        endTime:
          type: "select"
          data_key: "END_TIME"
        workercount:
          type: "number"
          data_key: "WORKER_COUNT"
        employerId:
          type: "text"
          data_key: "WORKSAFE_BC_ACCOUNT_NUMBER"
        employerName:
          type: "text"
          data_key: "EMPLOYER_NAME"
        addressLine1:
          type: "address"
          data_key: "EMPLOYER_ADDRESS"
    
    # Page 3: Project Information
    - project information:
        AsbestosCheck:
          type: "checkbox"
          data_key: "ASBESTOS_CHECK"
        LeadCheck:
          type: "checkbox"
          data_key: "LEAD_CHECK"
        OtherCheck:
          type: "checkbox"
          data_key: "OTHER_CHECK"
        employerId:
          type: "text"
          data_key: "WORKSAFE_BC_ACCOUNT_NUMBER"
        asbestosLicenseNumber:
          type: "text"
          data_key: "ASBESTOS_LICENSE_NUMBER"
        employerName:
          type: "text"
          data_key: "EMPLOYER_NAME"
        addressLine1:
          type: "address"
          data_key: "EMPLOYER_ADDRESS"
        WhoisInCharge:
          type: "radio"
          data_key: "IN_CHARGE"
        firstName:
          type: "text"
          data_key: "FIRST_NAME"
        lastName:
          type: "text"
          data_key: "LAST_NAME"
        inputTitle:
          type: "text"
          data_key: "JOB_TITLE"
        inputEmail:
          type: "text"
          data_key: "EMAIL"
        inputPhone:
          type: "text"
          data_key: "PHONE_NUMBER"
        asbestosCertificationNumber:
          type: "text"
          data_key: "ASBESTOS_CERTIFICATION_NUMBER"
        mulitipleEmployers:
          type: "radio"
          data_key: "MULTIPLE_EMPLOYERS"
        detailsText:
          type: "textarea"
          data_key: "OTHER_CONSULTING_FIRMS"
    
    # Page 4: Scope of Work
    - scope of work:
        DemolitionCheck:
          type: "checkbox"
          data_key: "DEMOLITION_CHECK"
        RepairCheck:
          type: "checkbox"
          data_key: "REPAIR_CHECK"
        RenovationCheck:
          type: "checkbox"
          data_key: "RENOVATION_CHECK"
        DismantlementCheck:
          type: "checkbox"
          data_key: "DISMANTLEMENT_CHECK"
        RemovalCheck:
          type: "checkbox"
          data_key: "REMOVAL_CHECK"
        EnclosureCheck:
          type: "checkbox"
          data_key: "ENCLOSURE_CHECK"
        EncapsulationCheck:
          type: "checkbox"
          data_key: "ENCAPSULATION_CHECK"
        RiskCalc:
          type: "radio"
          data_key: "RISK_CALC"

# Excel to PDF conversion configuration
EXCEL_TO_PDF:
  # Mapping from Excel column names to PDF field names
  # Format: "Excel Column Name": "PDF Field Name"
  field_mappings:
    "Name": "FullName"
    "Address": "StreetAddress"
    "Phone": "PhoneNumber"
    "Province": "Region"
    "Job Title": "JobTitle"
    "Department": "Dept"
  
  # Configuration for Excel file processing
  processing:
    # Sheet name to read from (if not specified, uses first sheet)
    default_sheet_name: "SiteDocsData"

